# AWS Cloudformation template for stacksets/org-ou
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organization Control Plane - Org OUs

Parameters:
  RootOuId:
    Type: String
    Description: Root OU Id

Resources:
  DevelopmentOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: Development
      ParentId: !Ref RootOuId

  InfrastructureOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: Infrastructure
      ParentId: !Ref RootOuId

  CicdOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: CI/CD
      ParentId: !Ref InfrastructureOu

  ObservabilityOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: Observability
      ParentId: !Ref InfrastructureOu

  SecurityOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: Security
      ParentId: !Ref RootOuId

  SuspendedOu:
    Type: AWS::Organizations::OrganizationalUnit
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: Suspended
      ParentId: !Ref RootOuId

Outputs:
  # We're only outputing top-level OU information because we need it elsewherew.
  SecurityOuId:
    Description: Security OU Id
    Value: !Ref SecurityOu
  SuspendedOuId:
    Description: Suspended OU Id
    Value: !Ref SuspendedOu
  InfrastructureOuId:
    Description: Infrastructure OU Id
    Value: !Ref InfrastructureOu
  DevelopmentOuId:
    Description: Development OU Id
    Value: !Ref DevelopmentOu