# AWS Cloudformation template for stacksets/org-ou
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organization Control Plane - Org OUs

Parameters:
  RootOuId:
    Type: String
    Description: Root OU Id

Resources:
  DevelopmentOu:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Development
      ParentId: !Ref RootOuId

  InfrastructureOu:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Infrastructure
      ParentId: !Ref RootOuId

  CicdOu:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: CI/CD
      ParentId: !Ref InfrastructureOu

  ObservabilityOu:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Observability
      ParentId: !Ref InfrastructureOu