AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure

Parameters:
  TargetOuIds:
    Type: String
    Description: List of OUs


Resources:
  ApigLoggingStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/apig-logging/template.yaml"

  BillingStackManagement:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/billing/template.yaml"

  EventBridgeLogging:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/eventbridge-logging/template.yaml"

  OuStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/org-ou/template.yaml"
      Parameters:
       RootOuId: !Ref TargetOuIds

  AccountStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/accounts/template.yaml"
      Parameters:
       SecurityOuId: 'ou-c834-uy4w2lbf'

