AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure

Parameters:
  TargetOuIds:
    Type: String
    Description: List of OUs
    Default: r-c834

Resources:
  BillingStackManagement:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/billing/template.yaml"

  DnsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/dns/template.yaml"

  OuStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/org-ou/template.yaml"
      Parameters:
       RootOuId: !Ref TargetOuIds
