AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure

Parameters:
  SecurityOuId:
    Type: String
    Description: ID of Security OU

Resources:

  AwsOrganization:
    Type: AWS::Organizations::Organization
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FeatureSet: ALL

  AwsOrganizationManagementAccount:
    Type: AWS::Organizations::Account
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccountName: Management
      Email: admin+aws-management@serverlessops.io

  OuStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/org-ou/template.yaml"
      Parameters:
        RootOuId: !GetAtt AwsOrganization.RootId

  AccountStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/org-accounts/template.yaml"
      Parameters:
        SecurityOuId: !Ref SecurityOuId

  ControlTowerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/control-tower/template.yaml"
      Parameters:
        AuditAccountId: !GetAtt AccountStack.Outputs.AuditAccountId
        LogArchiveAccountId: !GetAtt AccountStack.Outputs.LogArchiveAccountId