AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stacksets

Parameters:
  TargetOuIds:
    Type: String
    Description: List of OUs
    Default: r-c834

Resources:
  StacksetTemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-stacksets-${AWS::AccountId}-${AWS::Region}"

  BillingStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/billing/stackset.yaml"
      Parameters:
        TargetOuIds: !Ref TargetOuIds
        TargetRegions: us-east-1
        StacksetTemplateBucket: !Ref StacksetTemplateBucket
