AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS EventBridge Logging'

Resources:
  CwResourcePolicy:
      Type: AWS::Logs::ResourcePolicy
      Properties:
        PolicyName: "EventBridgeLoggingPolicy"
        PolicyDocument: !Sub |
            {
                "Statement": [
                    {
                        "Action": [
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ],
                        "Effect": "Allow",
                        "Principal": {
                            "Service": ["events.amazonaws.com", "delivery.logs.amazonaws.com"]
                        },
                        "Resource": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/events/*:*",
                        "Sid": "TrustEventsToStoreLogEvent"
                    }
                ],
                "Version": "2012-10-17"
            }