
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (GHA Build)

Parameters:
  StacksetTemplateBucket:
    Type: String
    Description: S3 bucket for stackset templates
  TargetOuIds:
    Type: CommaDelimitedList
    Description: List of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to

Resources:
  OrgCiCdSamDeploy:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: OrgCiCdSamDeploy
      Description: AWS SAM Deployment
      Parameters:
        - ParameterKey: AwsOrganizationId
          ParameterValue: 'o-txczodrxtj'
        - ParameterKey: BuildAccount
          ParameterValue: 'true'
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateURL: !Sub https://${StacksetTemplateBucket}.s3.amazonaws.com/gha-build/sam-deployment.yaml

  OrgCiCdGhaBuild:
    Type: AWS::CloudFormation::StackSet
    DependsOn: OrgCiCdSamDeploy
    Properties:
      StackSetName: OrgCiCdGhaBuild
      Description: GHA CI/CD Deployment Build
      Parameters:
        - ParameterKey: DeployBucketArn
          ParameterValue: '/org/cicd/SamDeployBucketArn'
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateURL: !Sub https://${StacksetTemplateBucket}.s3.amazonaws.com/gha-build/template.yaml
