AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub Actions Build Account

Parameters:
  IdpName:
    Type: String
    Description: "Name of IAM Identity Provider"
    Default: "token.actions.githubusercontent.com"

  DeployBucketArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "ARN of deployment bucket"

Resources:
  ###
  # IAM Roles
  ###
  GitHubActionsBuildRole:ws s3 sync --help
    Type: AWS::IAM::Role
    Properties:
      RoleName: "GitHubActionsBuildRole"
      Description: "GitHubActions Build Role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubActionsOidcProvider
            Condition:
              ForAllValues:StringLike:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                "token.actions.githubusercontent.com:sub": [
                  "repo:ServerlessOpsIO/*:ref:refs/heads/*",
                  "repo:ServerlessOpsIO/*:ref:refs/tags/*",
                  "repo:ServerlessOpsIO/*:environment:*",
                ]
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
      Policies:
        # Needed for SAM validate
        - PolicyName: Iam
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'iam:ListPolicies'
                Resource: '*'
        - PolicyName: SsmParams
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'ssm:GetParameter'
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:*:parameter/org/cicd/*"
        - PolicyName: SharedS3DeployBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 's3:List*'
                  - 's3:GetBucket*'
                Resource:
                  - !Ref DeployBucketArn
        - PolicyName: SharedS3DeployBucketObjects
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetObject*'
                  - 's3:List*'
                  - 's3:PutObject*'
                Resource:
                  # We group artifacts by GitHub org in case we need to accommodate more orgs.
                  - !Sub "${DeployBucketArn}/serverlessopsio/*"
                  # SAM templates are written at the root.
                  - !Sub "${DeployBucketArn}/*.template"
        - PolicyName: SharedS3DeployBucketObjectsDenyMainDelete
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Deny
                Action:
                  - 's3:DeleteObject'
                Resource:
                  - !Sub "${DeployBucketArn}/serverlessopsio/*/main/*"
                  - !Sub "${DeployBucketArn}/*.template"
        - PolicyName: STS
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                  - 'sts:TagSession'
                Resource:
                  - 'arn:aws:iam::*:role/GitHubActionsCfnDeployRole'
                  - 'arn:aws:iam::*:role/GitHubActionsTerraformDeployRole'
        - PolicyName: EcrLogin
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'
        - PolicyName: EcrPull
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchGetImage'
                  - 'ecr:GetDownloadUrlForLayer'
                Resource:
                  - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"
        - PolicyName: EcrPublish
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:PutImage'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:CreateRepository'
                  - 'ecr:SetRepositoryPolicy'
                Resource:
                  - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/serverlessops/*"

  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Url: !Sub "https://${IdpName}"


  ###
  #SSM Parameters
  ###
  GitHubActionsIamRoleArnSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/org/cicd/GitHubActionsBuildRoleArn"
      Type: "String"
      Description: "GitHubActions IAM Role ARN"
      Value: !GetAtt GitHubActionsBuildRole.Arn