AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organization Control Plane - IAM IdC SSO

Parameters: {}

Resources:
  SsoInstance:
    Type: AWS::SSO::Instance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: ServerlessOps

Outputs:
  SsoInstanceArn:
    Description: SSO Instance ARN
    Value: !GetAtt SsoInstance.InstanceArn

  SsoInstanceIdentityStoreId:
    Description: SSO Instance IdentityStoreId
    Value: !GetAtt SsoInstance.IdentityStoreId

  SsoOwnerAccountId:
    Description: SSO Owner Account Id
    Value: !GetAtt SsoInstance.OwnerAccountId