AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organization Control Plane - AWS Organization

Parameters: {}

Resources:
  AwsOrganization:
    Type: AWS::Organizations::Organization
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FeatureSet: ALL

  AwsOrganizationManagementAccount:
    Type: AWS::Organizations::Account
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccountName: Management
      Email: admin+aws-management@serverlessops.io

Outputs:
  OrganizationId:
    Description: The AWS Organization ID
    Value: !Ref AwsOrganization

  OrganizationArn:
    Description: The AWS Organization ARN
    Value: !GetAtt AwsOrganization.Arn

  OrganizationRootId:
    Description: The AWS Organization Root ID
    Value: !GetAtt AwsOrganization.RootId

  OrganizationManagementAccountId:
    Description: The AWS Organization Management Account ID
    Value: !GetAtt AwsOrganization.ManagementAccountId

  OrganizationManagementAccountArn:
    Description: The AWS Organization Management Account ARN
    Value: !GetAtt AwsOrganization.ManagementAccountArn