AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organization Control Plane - AWS Organization

Parameters: {}

Resources:
  AwsOrganization:
    Type: AWS::Organizations::Organization
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FeatureSet: ALL

  AwsOrganizationManagementAccount:
    Type: AWS::Organizations::Account
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccountName: Management
      Email: admin+aws-management@serverlessops.io
