Metadata:
  localTemplateFile: &template_body ./template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (APIG Logging)

Parameters:
  TargetOuIds:
    Type: CommaDelimitedList
    Description: List of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to

Resources:
  ApigLogging:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: ApigLogging
      Description: API Gateway Logging
      CallAs: DELEGATED_ADMIN
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      Capabilities:
        - CAPABILITY_NAMED_IAM
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *template_body
