AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS APIG Logging'

Resources:
  CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ApigCloudWatchLogsRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

  ApigAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn